# Generated by Django 6.0.2 on 2026-02-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejercicio', models.CharField(max_length=45)),
                ('descripcion_ejercicio', models.TextField(blank=True, null=True)),
                ('musculo_principal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rutina', models.CharField(max_length=100)),
                ('descripcion_rutina', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=45)),
                ('tipo_cuenta', models.CharField(default='free', max_length=45)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.rutina')),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.usuario'),
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso_usado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('repeticiones_realizadas', models.PositiveIntegerField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.usuario')),
            ],
        ),
    ]
